# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeneratePRD = channel.unary_unary(
                '/agent.AgentService/GeneratePRD',
                request_serializer=agent__pb2.PRDRequest.SerializeToString,
                response_deserializer=agent__pb2.PRDResponse.FromString,
                _registered_method=True)
        self.GenerateCode = channel.unary_unary(
                '/agent.AgentService/GenerateCode',
                request_serializer=agent__pb2.CodeRequest.SerializeToString,
                response_deserializer=agent__pb2.CodeResponse.FromString,
                _registered_method=True)
        self.GenerateTests = channel.unary_unary(
                '/agent.AgentService/GenerateTests',
                request_serializer=agent__pb2.TestRequest.SerializeToString,
                response_deserializer=agent__pb2.TestResponse.FromString,
                _registered_method=True)
        self.TriggerDeployment = channel.unary_unary(
                '/agent.AgentService/TriggerDeployment',
                request_serializer=agent__pb2.DeployRequest.SerializeToString,
                response_deserializer=agent__pb2.DeployResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/agent.AgentService/Ping',
                request_serializer=agent__pb2.PingRequest.SerializeToString,
                response_deserializer=agent__pb2.PongResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GeneratePRD(self, request, context):
        """PM Agent: 生成 PRD
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateCode(self, request, context):
        """Dev Agent: 生成代码
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTests(self, request, context):
        """Test Agent: 生成测试用例
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerDeployment(self, request, context):
        """Ops Agent: 触发部署
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """测试连通性
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeneratePRD': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePRD,
                    request_deserializer=agent__pb2.PRDRequest.FromString,
                    response_serializer=agent__pb2.PRDResponse.SerializeToString,
            ),
            'GenerateCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCode,
                    request_deserializer=agent__pb2.CodeRequest.FromString,
                    response_serializer=agent__pb2.CodeResponse.SerializeToString,
            ),
            'GenerateTests': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTests,
                    request_deserializer=agent__pb2.TestRequest.FromString,
                    response_serializer=agent__pb2.TestResponse.SerializeToString,
            ),
            'TriggerDeployment': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerDeployment,
                    request_deserializer=agent__pb2.DeployRequest.FromString,
                    response_serializer=agent__pb2.DeployResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=agent__pb2.PingRequest.FromString,
                    response_serializer=agent__pb2.PongResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GeneratePRD(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/GeneratePRD',
            agent__pb2.PRDRequest.SerializeToString,
            agent__pb2.PRDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/GenerateCode',
            agent__pb2.CodeRequest.SerializeToString,
            agent__pb2.CodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateTests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/GenerateTests',
            agent__pb2.TestRequest.SerializeToString,
            agent__pb2.TestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerDeployment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/TriggerDeployment',
            agent__pb2.DeployRequest.SerializeToString,
            agent__pb2.DeployResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/Ping',
            agent__pb2.PingRequest.SerializeToString,
            agent__pb2.PongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
