// Task model definitions
package models

import "time"

// Task represents a task in the task board.
type Task struct {
	ID                string    `json:"id"`
	Title             string    `json:"title"`
	Type              string    `json:"type"`                       // code/test/deploy/document
	AgentType         string    `json:"agent_type"`                 // coder/tester/deployer/planner
	Priority          string    `json:"priority"`                  // high/medium/low
	State             string    `json:"state"`                     // pending/running/testing/passed/failed/cancelled/completed
	Assignee          string    `json:"assignee"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	EstimatedDuration int       `json:"estimated_duration"` // seconds
	ActualDuration    int       `json:"actual_duration"`   // seconds
	RetryCount        int       `json:"retry_count"`
	Version           int       `json:"version"` // optimistic locking
}

// TaskDetail represents a task with associated documents and rollback logs.
type TaskDetail struct {
	Task          Task           `json:"task"`
	Documents     []Document     `json:"documents,omitempty"`
	RollbackLogs  []TaskRollbackLog  `json:"rollback_logs,omitempty"`
}

// Document represents a document generated by a task.
type Document struct {
	ID        string    `json:"id"`
	TaskID    string    `json:"task_id"`
	Filename  string    `json:"filename"`
	FileType  string    `json:"file_type"` // md/docx/pdf/txt
	FileSize  int       `json:"file_size"`
	Summary   string    `json:"summary"`
	RawText   string    `json:"raw_text,omitempty"`
	CreatedAt time.Time `json:"created_at"`
}

// TaskRollbackLog represents a rollback log entry for a task.
type TaskRollbackLog struct {
	ID            string     `json:"id"`
	TaskID        string     `json:"task_id"`
	TargetVersion string     `json:"target_version"`
	Step          int        `json:"step"`
	StepName      string     `json:"step_name"`
	Status        string     `json:"status"` // pending/completed/failed
	ErrorMessage  string     `json:"error_message,omitempty"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	CompletedAt   *time.Time `json:"completed_at,omitempty"`
	RetryCount    int        `json:"retry_count"`
	GitRevertSHA  string     `json:"github_revert_sha,omitempty"`
	DeploymentID  string     `json:"deployment_id,omitempty"`
	LastRollbackAt *time.Time `json:"last_rollback_at,omitempty"`
}

// TaskLog represents a single log entry for task execution.
type TaskLog struct {
	ID        string    `json:"id"`
	TaskID    string    `json:"task_id"`
	Timestamp time.Time `json:"timestamp"`
	Level     string    `json:"level"` // INFO/DEBUG/ERROR/WARN
	Agent     string    `json:"agent"`
	Message   string    `json:"message"`
}

// TaskStateTransitionRequest represents a state transition API request.
type TaskStateTransitionRequest struct {
	FromState string      `json:"from_state"`
	ToState   string      `json:"to_state"`
	Logs      []TaskLog  `json:"logs,omitempty"`
}
